// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:city_eye/flavors.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return F.name == Flavor.production.name
            ? android
            : F.name == Flavor.development.name
                ? androidDevelopment
                : F.name == Flavor.nicetouchproduction.name
                    ? androidNiceTouch
                    : F.name == Flavor.nicetouchdevelopment.name
                        ? androidNiceTouchDevelopment
                        : android;
      case TargetPlatform.iOS:
        return F.name == Flavor.production.name
            ? ios
            : F.name == Flavor.development.name
                ? iosDevelopment
                : F.name == Flavor.nicetouchproduction.name
                    ? iosNiceTouch
                    : F.name == Flavor.nicetouchdevelopment.name
                        ? iosNiceTouchDevelopment
                        : ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB01pNDLB4Y4ugVoL0M4fl6RSruA29p9Tg',
    appId: '1:303235547553:android:1ee302e7fc510e50fb4be0',
    messagingSenderId: '303235547553',
    projectId: 'cityeye-7c456',
    storageBucket: 'cityeye-7c456.appspot.com',
  );

  static const FirebaseOptions androidDevelopment = FirebaseOptions(
    apiKey: 'AIzaSyB01pNDLB4Y4ugVoL0M4fl6RSruA29p9Tg',
    appId: '1:303235547553:android:326ef1eb54be0509fb4be0',
    messagingSenderId: '303235547553',
    projectId: 'cityeye-7c456',
    storageBucket: 'cityeye-7c456.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS7zDryuZV2hQ47PRmdfSx1hrBLFt2omU',
    appId: '1:303235547553:ios:0018f5fd41022a2cfb4be0',
    messagingSenderId: '303235547553',
    projectId: 'cityeye-7c456',
    storageBucket: 'cityeye-7c456.appspot.com',
    iosBundleId: 'com.sprinteye.cityeye.app',
  );

  static const FirebaseOptions iosDevelopment = FirebaseOptions(
    apiKey: 'AIzaSyCS7zDryuZV2hQ47PRmdfSx1hrBLFt2omU',
    appId: '1:303235547553:ios:f3c92da514929067fb4be0',
    messagingSenderId: '303235547553',
    projectId: 'cityeye-7c456',
    storageBucket: 'cityeye-7c456.appspot.com',
    iosBundleId: 'com.sprinteye.cityeye.app.development',
  );

  static const FirebaseOptions androidNiceTouch = FirebaseOptions(
    apiKey: 'AIzaSyB01pNDLB4Y4ugVoL0M4fl6RSruA29p9Tg',
    appId: '1:303235547553:android:4f628048e12ecea5fb4be0',
    messagingSenderId: '303235547553',
    projectId: 'cityeye-7c456',
    storageBucket: 'cityeye-7c456.appspot.com',
  );

  static const FirebaseOptions androidNiceTouchDevelopment = FirebaseOptions(
    apiKey: 'AIzaSyB01pNDLB4Y4ugVoL0M4fl6RSruA29p9Tg',
    appId: '1:303235547553:android:83474cdb8753389bfb4be0',
    messagingSenderId: '303235547553',
    projectId: 'cityeye-7c456',
    storageBucket: 'cityeye-7c456.appspot.com',
  );

  static const FirebaseOptions iosNiceTouch = FirebaseOptions(
    apiKey: 'AIzaSyCS7zDryuZV2hQ47PRmdfSx1hrBLFt2omU',
    appId: '1:303235547553:ios:adbeb4090f4f4aa7fb4be0',
    messagingSenderId: '303235547553',
    projectId: 'cityeye-7c456',
    storageBucket: 'cityeye-7c456.appspot.com',
    iosBundleId: 'com.sprinteye.cityeye.nicetouch',
  );

  static const FirebaseOptions iosNiceTouchDevelopment = FirebaseOptions(
    apiKey: 'AIzaSyCS7zDryuZV2hQ47PRmdfSx1hrBLFt2omU',
    appId: '1:303235547553:ios:a4b7ac6e76a139cefb4be0',
    messagingSenderId: '303235547553',
    projectId: 'cityeye-7c456',
    storageBucket: 'cityeye-7c456.appspot.com',
    iosBundleId: 'com.sprinteye.cityeye.nicetouch.development',
  );
}
